apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: security-api
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: security-api
              tier: security
        spec:
            containers:
            - name: security-api
              image: sleepingtalent/security-api:1.0.21-RC
              env:
              - name: CONFIG_URL
                value: http://ae72c3afb915511e795a406fc096cf91-818673775.us-west-2.elb.amazonaws.com:1111/config-api/
              ports:
              - containerPort: 1112
