apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: security-api
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: security-api
              tier: security
        spec:
            containers:
            - name: security-api
              image: sleepingtalent/security-api:1.0.25-RC
              env:
              - name: CONFIG_URL
                value: http://a7248fd52b28911e798ab0a429a68c51-925490504.eu-west-1.elb.amazonaws.com:1111/config-api/
              ports:
              - containerPort: 1112
