apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: security-api
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: security-api
              tier: security
        spec:
            containers:
            - name: security-api
              image: sleepingtalent/security-api:1.0.31
              env:
              - name: CONFIG_URL
                value: http://config-api-gateway:1111/config-api/
              ports:
              - containerPort: 1112

---

apiVersion: v1
kind: Service
metadata:
    name: security-api-gateway
    labels:
        app: security-api
        tier: security
spec:
    type: LoadBalancer
    ports:
    - port: 1112
    selector:
        app: security-api
        tier: security