def pomLocation = "security-api-parent"
def dockerRepoName = "sleepingtalent/security-api"
def targetLocation = "security-api-parent/security-api/target"
def version

node {
  def img

   stage('Checkout') {
     checkout scm
   }

   stage('Build Application') {
     sh 'mvn -B -V -U -e -f '+pomLocation+'/pom.xml clean package'
   }

   stage('Package Image') {
     def pom = readMavenPom file: pomLocation+'/pom.xml'
     version = pom.version
     img = docker.build(dockerRepoName+':'+version, targetLocation)
   }

   stage('Push Image') {
     docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
         img.push()
         img.push("latest")
     }
   }

   stage('Remove Local Image') {
        sh 'docker rmi -f registry.hub.docker.com/'+dockerRepoName+':latest'
        sh 'docker rmi -f registry.hub.docker.com/'+dockerRepoName+':'+version
        sh 'docker rmi -f '+dockerRepoName+':'+version
   }

}